### ISSUE TITLE
Build error with xcaddy

### ISSUE THREAD

**Issue by androidacy** [sillygod/cdp-cache#39] opened 2021-04-10 17:33 UTC
```
/home/unixandria/go/pkg/mod/github.com/sillygod/cdp-cache@v0.4.3/endpoint.go:141:4: unknown field 'Code' in struct literal of type caddy.APIError
```
This prevents building with xcaddy

**Comment by sillygod** [comment] 2021-04-11 04:28
Hi @androidacy,

Could you show what command you've entered to build the executable?

I've tried this

```sh
xcaddy build v2.0.0 --with github.com/sillygod/cdp-cache 
```

It works well. 

I guess you didn't specify the caddy's version.

**Comment by androidacy** [comment] 2021-04-11 15:38
I build 2.4.x, not 2.0.9 (I don't specify caddy version)

**Comment by androidacy** [comment] 2021-04-11 15:40
I have no reason to run an outdated version of caddy, as even stable is 2.3.x

**Comment by sillygod** [comment] 2021-04-12 01:28
Currently, this plugin supports caddy's version up to 2.1.1 because I develop this at that time. There are some breaking changes in the newer caddy's version.

I have to spend efforts to upgrade the caddy's version

**Comment by sillygod** [comment] 2021-04-12 01:34
I will close this issue because it's not a bug.  I create another issue as a wishlist. #41

**Closed by sillygod** 2021-04-12 01:34 UTC
Labels: question
